name: Push - AWS GPU

on:
  push:
    branches:
      - main
      - 'release-*'
      - '*' # TODO: Remove this before merging
    tags:
      - '*'
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  run-tests:
    uses: ./.github/workflows/aws_gpu_tests.yml
    secrets: inherit
